// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGIuSKm8vuNVQFmAMyFfr32d-jzcqXSbo',
    appId: '1:308637159495:web:c94c3995460155a3252162',
    messagingSenderId: '308637159495',
    projectId: 'barcodesearch',
    authDomain: 'barcodesearch.firebaseapp.com',
    storageBucket: 'barcodesearch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aS6Jp3lwohryFE2vHKIcUvDxcHfnr2s',
    appId: '1:308637159495:android:cc74245facbcc750252162',
    messagingSenderId: '308637159495',
    projectId: 'barcodesearch',
    storageBucket: 'barcodesearch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7G0k5D1A6ZGWgkoL56EGEShy1c71q3RQ',
    appId: '1:308637159495:ios:c1137b58bd3f52be252162',
    messagingSenderId: '308637159495',
    projectId: 'barcodesearch',
    storageBucket: 'barcodesearch.appspot.com',
    iosClientId: '308637159495-aqe6mojf0d9bgsqrlcii7om8578bnejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcodesearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7G0k5D1A6ZGWgkoL56EGEShy1c71q3RQ',
    appId: '1:308637159495:ios:c1137b58bd3f52be252162',
    messagingSenderId: '308637159495',
    projectId: 'barcodesearch',
    storageBucket: 'barcodesearch.appspot.com',
    iosClientId: '308637159495-aqe6mojf0d9bgsqrlcii7om8578bnejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcodesearch',
  );
}
